### ISSUE TITLE
no parsing in V0.14.1

### ISSUE THREAD

**Issue by MarcoLaser** [jens-maus/node-ical#173]
I use node-ical via the iobroker adapter, since the update to version 0.14.1 the [calender](https://wbl.de/pdf/ical2022.php?t=1640021970&strasse=Zum+Pier&no_behaelter_14=0&no_container_14=1&no_behaelter_4=1&no_container_4=1&no_gelb=0&no_gelb_container=1&no_bio=0&no_papier=0&no_papier_container=1) I am using is not being parsed correctly.
Unfortunately I cannot provide any errormessages, but with V 0.13 everything is working fine.
also see [iobroker.ical Issue](https://github.com/iobroker-community-adapters/ioBroker.ical/issues/338)

**Comment by Apollon77** [comment]
The only thing I found that could affect parsing is https://github.com/jens-maus/node-ical/commit/45792f5e2bb7aa6d24993cee82342ffb7da5a068 

In fact empty lines should simply be ignored from the rest of the logic, but I'm also unsure if this regex is compatble with  the logic in https://github.com/jens-maus/node-ical/commit/45792f5e2bb7aa6d24993cee82342ffb7da5a068#diff-a717da36dca416b92146c74d0e6a1cae778967192eda55915710200af50ec829L599-L602 but should also be unrelated

**Comment by Apollon77** [comment]
Proofed https://github.com/iobroker-community-adapters/ioBroker.ical/issues/338#issuecomment-1073038823

So a file with content like

```
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//Stadt Worms//ebwo Abfallkalender//EN
METHOD:PUBLISH


BEGIN:VEVENT
UID:20211223T130313Z-61c46581548585.20207021@worms.de
SUMMARY;CHARSET=UTF-8:Gelbe Tonne Abholung - Gaustraße 97-165; 96-210
DESCRIPTION:Ein Service des Entsorgungs- und Baubetrieb der Stadt Worms - Stand: 23.12.2021 13:03
CLASS:PUBLIC
DTSTART;VALUE=DATE:20220107
DTSTAMP:20211223T130313Z
END:VEVENT


BEGIN:VEVENT
UID:20211223T130313Z-61c465815486f4.83445781@worms.de
SUMMARY;CHARSET=UTF-8:Gelbe Tonne Abholung - Gaustraße 97-165; 96-210
DESCRIPTION:Ein Service des Entsorgungs- und Baubetrieb der Stadt Worms - Stand: 23.12.2021 13:03
CLASS:PUBLIC
DTSTART;VALUE=DATE:20220121
DTSTAMP:20211223T130313Z
END:VEVENT
```

can not be parsed anymore.

@f8k8 Can you please look into this because that regex change in https://github.com/jens-maus/node-ical/pull/101 was from you ...

**Comment by f8k8** [comment]
I was unable to reproduce the issue from copy / pasting the example in [your comment](https://github.com/jens-maus/node-ical/issues/173#issuecomment-1073055297), but I did get no events when directly using the ICS downloaded from the calendar linked in the [original post](https://github.com/jens-maus/node-ical/issues/173#issue-1092103696).

The issue is that the calendar does not conform to the RFC 5545 specification. [Section 3.1 of the specification](https://datatracker.ietf.org/doc/html/rfc5545#section-3.1) states:

> The iCalendar object is organized into individual lines of text,
   called content lines.  Content lines are delimited by a line break,
   which is a CRLF sequence (CR character followed by LF character).

However, the calendar downloaded has some lines which end with LF only, not CRLF:
![image](https://user-images.githubusercontent.com/1764665/159139122-6545f325-668b-49e2-a896-beea963db3db.png)

This is why in the [iobroker issue](https://github.com/iobroker-community-adapters/ioBroker.ical/issues/338), I believe they say it works when imported into nextcloud, as the nextcloud provided ICS will be correctly formatted.

Although the specification says that lines are terminated with CRLF, this library does attempt to handle files which end with LF only by calling [getLineBreakChar](https://github.com/jens-maus/node-ical/blob/322be589962e1105d57affd4ac8a4210febaab8f/ical.js#L726) and splitting by the line break character detected. However, because this example mixes some lines with CRLF and some with LF, the CR characters are kept in at the end of each line and so aren't parsed correctly.

I think it would be up to @jens-maus as to how they want to handle calendars which don't conform to the spec in this way. I think the easiest way would be to replace all LF only line endings with CRLF before splitting into lines, which would remove the need for the `getLineBreakChar` test.

**Comment by Apollon77** [comment]
Good catch @f8k8 ... Thank you for the details! I think the "reason" for this issue to appear is the regex change that includes the "line end" :-)

**Comment by f8k8** [comment]
Yes, the reason you're seeing it now is due to the regex change, but there was never a guarantee that the library would correctly parse an invalid input. Unless @jens-maus wants to add in specific support for this, then the solution is to make sure the calendar data is correctly formatted before passing it to this library. It's not really a bug but a feature request to add support for mixing invalid line endings.

**Comment by Apollon77** [comment]
@f8k8 in fact it was working before ... because the former regex "just" checked that in the line k&v are existing ... now the regex is "more accurate" whcih kind of breaks support of such strange files ... so ... But I would not start discussing if bug or feature because in fact hard to say.

For me it is as follows: The called ics data are coming "out of the wild", that means that such invalid files are provided out there, so I think the library should support it ... (did you ever tried to describe this to a whatever company what they do wrong ... and "all others" ignore it? ;-)

But yes the change should be in https://github.com/jens-maus/node-ical/blob/master/ical.js#L726-L727

In fact I would normalize it completely to \r\n

**Comment by f8k8** [comment]
Yeah, I get what you're saying about the broken iCals being "out in the wild" 🙂. I'd say the PR looks good. Splitting with the optional CR is cleaner than preprocessing, so over to @jens-maus now.
