### ISSUE TITLE
Module not found: Can't resolve 'fs'

### ISSUE THREAD

**Issue by MattHeslington** [jens-maus/node-ical#202]
Hello Jens,

I'm receiving the above error when try to parse a local .ics file. I understand the fs package has been depreciated - I installed fs-extra instead, which is described as a drop-in replacement, and changed the reference in node_modules/node-ical/node-ical.js to 
`const fs = require('fs-extra')` but I'm still getting the error. 

Can anyone help me out, please?
Cheers, Matt

**Comment by jens-maus** [comment]
full example please. I can't see any "Can't resolve fs" error whatsoever.

**Comment by MattHeslington** [comment]
Hello Jens,

Thanks for the reply.

`
import ical from 'node-ical'

function parseIcal() {
        const events = ical.sync.parseFile('/ical-test.ics')
        for (const event of Object.values(events)) {
            console.log(
                'Summary: ' + event.summary + '\nDescription: ' + event.description + '\nStart Date: ' + event.start.toISOString() + '\n'
            )
        }
    }`

![Screenshot 2022-06-17 at 21 54 04](https://user-images.githubusercontent.com/8208896/174312335-338b8b6f-b48b-442e-b966-1ff2a13918cf.jpg)

**Comment by jens-maus** [comment]
Which nodejs version do you use?

**Comment by jens-maus** [comment]
You are obviously trying to use node-ical with nextjs, which however is not supported at that time and look here to understand the fs module not found error you are facing:

https://stackoverflow.com/questions/64926174/module-not-found-cant-resolve-fs-in-next-js-application

Thus, this seems to be a pure usage error on your end, because node-ical is (the name implies it) supposed to be used within pure nodejs environments.

**Comment by MattHeslington** [comment]
Ok cheers, thanks for clearing that up.
