### ISSUE TITLE
Bug in rrule > 2.7.2

### ISSUE THREAD

**Issue by runely** [jens-maus/node-ical#291]
After updating `node-ical` from **0.16.1** to **0.17.0** in my app i see a 26% RAM increase. My app runs on Homey which doesn't have all the power in the world. And this increase makes it use to much RAM and Homey kills it.

If i downgrade back to **0.16.1** again then it's back to the normal RAM usage.

The only big change in `node-ical` **0.17.0** seems to be `RRule` bumped from 2.6.4 to 2.8.1.
And there seems to be a [bug on RRule > 2.7.2](https://github.com/jkbrzt/rrule/issues/608) (more issues that seems to be related to that issue). In fact it seems that versions after 2.7.1 is removed from github, but still present on npm.js

Is the bug in RRule the culprit of the RAM increase, i don't know. But downgrading RRule to 2.7.0 or 2.7.1 might be a good start

**Comment by jens-maus** [comment]
Indeed strange there there is a 2.8.1 version on npm but the github project itself does not have that release anymore and that there is only 2.7.1 atm. But well, your requests sounds reasonable, so I changed the required rrule version to 2.7.1 to play on the save side. And I also released 0.17.1 of node-ical accordingly. So please have a look if this also solves your RAM issues beside the other issues with newer rrule versions.

**Comment by runely** [comment]
Downgrade to `2.7.1` did not help. The RAM increase is still there

**Comment by jens-maus** [comment]
I already guessed that. I think that might be either due to other dependency changes or due to the fact that rrule 2.7 does not use Luxon anymore itself (because it is buggy) but does now implement all that itself…

**Comment by tetron** [comment]
It seems that rrule 2.7.1 has at least one serious bug that causes it to fail to return recurring events properly.  Upgrading to rrule 2.8.1 fixes it.  I am finding that node-ical 0.17.0 (which depends on 2.8.1) generates events correctly, but the node-ical 0.17.1, which was downgraded to rrule 2.7.1, has broken recurring events.  I am pinning node-ical 0.17.0 for myself but node-ical probably needs to choose between rrule 2.8.1+ or downgrade to rrule 2.6, because rrule 2.7.1 is not usable.

(I'm using MagicMirror and people are advising people to install a different node-ical version because of this issue https://github.com/MagicMirrorOrg/MagicMirror/issues/3351)

**Comment by jens-maus** [comment]
FYI: I just upgraded rrule dependency again to use version 2.8.1 in node-ical 0.17.2 as this version does not seem to be broken regarding recurrent event handling.
